syntax = "proto3";
package dataset_on_demand;

option go_package = "github.com/imi-bigpicture/bp-dod-sda-gateway/grpc_gen/go/v1";


service DatasetOnDemandService {
  rpc NewOriginDataset(NewOriginDatasetRequest) returns (NewOriginDatasetResponse);
  rpc RequestDatasetCreation(RequestDatasetCreationRequest) returns (RequestDatasetCreationResponse);
  rpc GetDoDDataset(GetDoDDatasetRequest) returns (GetDoDDatasetResponse);
  rpc ListDoDDatasets(ListDoDDatasetsRequest) returns (ListDoDDatasetsResponse);
}

message NewOriginDatasetRequest {
  string dataset_accession = 1;
}
message NewOriginDatasetResponse {
}
message RequestDatasetCreationRequest {
  repeated string image_aliases = 1;
  string user = 2;
}
message RequestDatasetCreationResponse {
  string dod_dataset_accession = 1;
}
message GetDoDDatasetRequest {
  string dod_dataset_accession = 1;
}
message GetDoDDatasetResponse {
  DoDDataset dod_dataset = 1;
}
message ListDoDDatasetsRequest {

}
message ListDoDDatasetsResponse {
 repeated DoDDataset dod_datasets = 1;
}



message DoDDataset {
  string dataset_accession = 1;
  enum Status {
    STATUS_INVALID = 0;
    STATUS_CREATING = 1;
    STATUS_CREATED = 2;
  }
  Status status = 2;
}



